image: ctcampbelldocker/veracode-ci-examples

stages:
    - build
    - scan

package:
    stage: build
    script:
        - zip -r veracode.zip *.py
    artifacts:
        paths:
            - git archive -o veracode.zip HEAD
    
veracode-policy-scan:
    stage: scan
    only:
        - schedules
        - master
    script:
        - java -jar --add-modules /veracode/veracode-wrapper.jar -vid ${TEAM_ANALYSISCENTER_ID} -vkey ${TEAM_ANALYSISCENTER_KEY}
          -action UploadAndScan -appname "${CI_PROJECT_NAME}" -createprofile true -autoscan true
          -filepath veracode.zip -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"
